<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="guestmsg2.aspx.vb" Inherits="homesomee.guestmsg2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
   <div>
    
        <span class="style1">&nbsp;&nbsp;<asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="http://www.hacker1.somee.com/mapsql3">回前頁</asp:HyperLink>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <br />
        留言版:<br />
        <br />
&nbsp;<asp:Label ID="資料起日" runat="server" Height="20px" Text="資料起日:" Width="108px"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:TextBox ID="起" runat="server" Height="25px" Width="100px" 
        style="margin-left: 0px" Font-Size="Medium">1</asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Label ID="迄日" runat="server" Height="20px" Text="迄日:" Width="100px"></asp:Label>
    <asp:TextBox ID="迄" runat="server" Height="25px" Width="100px" Font-Size="Medium">100000</asp:TextBox>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
    &nbsp;查詢欄位:<asp:DropDownList ID="查詢欄位名稱" runat="server" Font-Size="Medium" 
            Height="25px" Width="100px">
        <asp:ListItem Selected="True">識別碼</asp:ListItem>
            <asp:ListItem>name1</asp:ListItem>
            <asp:ListItem>mail1</asp:ListItem>
            <asp:ListItem>word1</asp:ListItem>
    </asp:DropDownList>
&nbsp;&nbsp;&nbsp;&nbsp; 排序欄位<asp:DropDownList ID="排序欄位" runat="server" 
            Font-Size="Medium" Height="25px" Width="100px">
        <asp:ListItem Selected="True">識別碼</asp:ListItem>
            <asp:ListItem>name1</asp:ListItem>
            <asp:ListItem>mail1</asp:ListItem>
            <asp:ListItem>word1</asp:ListItem>
    </asp:DropDownList>
        &nbsp;&nbsp; <asp:Button ID="Button2" runat="server" Height="30px" Text="搜尋" Width="50px" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (相似查詢:<asp:TextBox ID="keyword" 
            runat="server" Height="25px" Width="140px" Font-Size="Medium"></asp:TextBox>
        <asp:Button ID="Button5" runat="server" Height="30px" Text="搜尋" 
            Width="50px" />
        )&nbsp;<br />
        &nbsp;<br />    
                <asp:GridView ID="GridView1" runat="server" CellPadding="4" 
            ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" DataKeyNames="識別碼" AutoGenerateColumns="False">
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <Columns>
                        <asp:BoundField DataField="識別碼" HeaderText="識別碼">
                        <ControlStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <FooterStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                        </asp:BoundField>
                        <asp:BoundField DataField="name1" HeaderText="姓名">
                        <ControlStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                        </asp:BoundField>
                        <asp:BoundField DataField="mail1" HeaderText="mail1">
                        <ControlStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                        </asp:BoundField>
                        <asp:BoundField DataField="word1" HeaderText="留言內容">
                        <ControlStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                        </asp:BoundField>
                        <asp:BoundField DataField="時間戳記" HeaderText="日期">
                        <ControlStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                        <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                        </asp:BoundField>
                    </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <AlternatingRowStyle BackColor="White" />
                    <SortedAscendingCellStyle BackColor="#FDF5AC" />
                    <SortedAscendingHeaderStyle BackColor="#4D0000" />
                    <SortedDescendingCellStyle BackColor="#FCF6C0" />
                    <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <br />
                <asp:GridView ID="GridView2" runat="server" CellPadding="4" 
    ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" 
    AutoGenerateEditButton="True" DataKeyNames="識別碼" AutoGenerateColumns="False">
    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <Columns>
                <asp:BoundField DataField="識別碼" HeaderText="識別碼">
                <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                </asp:BoundField>
                <asp:BoundField DataField="name1" HeaderText="姓名">
                <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                </asp:BoundField>
                <asp:BoundField DataField="mail1" HeaderText="mail">
                <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                </asp:BoundField>
                <asp:BoundField DataField="word1" HeaderText="留言內容">
                <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                </asp:BoundField>
                <asp:BoundField DataField="時間戳記" HeaderText="時間戳記">
                <HeaderStyle Font-Names="標楷體" Font-Size="X-Large" />
                <ItemStyle Font-Names="標楷體" Font-Size="Large" />
                </asp:BoundField>
            </Columns>
    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
    <AlternatingRowStyle BackColor="White" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
</asp:GridView>
<br />
<br />
        增加留言(一)<br />
        <br />
         姓名:
        <asp:TextBox ID="poemname" runat="server" Width="147px"></asp:TextBox>&nbsp; 
        郵件地址 :
        <asp:TextBox ID="poemmail" runat="server" Width="238px">abc@xyz</asp:TextBox>&nbsp; 日期 :
        <asp:TextBox ID="poemtime" runat="server"></asp:TextBox>
        <br />
        請輸入留言內容:<br />
&nbsp;<asp:TextBox ID="poemcontent" runat="server" Height="110px" TextMode="MultiLine" 
            Width="522px"></asp:TextBox><br />
        &nbsp; &nbsp;
        <asp:Button ID="增加留言" runat="server" Text="增加留言" ToolTip="欄位皆須有資料" /><br />
        <br />
        <asp:Button ID="增加留言0" runat="server" Text="刷新資料" />
        <br />
        <asp:GridView ID="GridView3" runat="server" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="識別碼" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
                <asp:BoundField DataField="識別碼" HeaderText="識別碼" InsertVisible="False" ReadOnly="True" SortExpression="識別碼" />
                <asp:BoundField DataField="name1" HeaderText="name1" SortExpression="name1" />
                <asp:BoundField DataField="mail1" HeaderText="mail1" SortExpression="mail1" />
                <asp:BoundField DataField="word1" HeaderText="word1" SortExpression="word1" />
                <asp:BoundField DataField="時間戳記" HeaderText="時間戳記" SortExpression="時間戳記" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:pokomonConnectionString %>" DeleteCommand="DELETE FROM [textmsg1] WHERE [識別碼] = @original_識別碼 AND (([name1] = @original_name1) OR ([name1] IS NULL AND @original_name1 IS NULL)) AND (([mail1] = @original_mail1) OR ([mail1] IS NULL AND @original_mail1 IS NULL)) AND (([word1] = @original_word1) OR ([word1] IS NULL AND @original_word1 IS NULL)) AND (([時間戳記] = @original_時間戳記) OR ([時間戳記] IS NULL AND @original_時間戳記 IS NULL))" InsertCommand="INSERT INTO [textmsg1] ([name1], [mail1], [word1], [時間戳記]) VALUES (@name1, @mail1, @word1, @時間戳記)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [textmsg1] ORDER BY [識別碼]" UpdateCommand="UPDATE [textmsg1] SET [name1] = @name1, [mail1] = @mail1, [word1] = @word1, [時間戳記] = @時間戳記 WHERE [識別碼] = @original_識別碼 AND (([name1] = @original_name1) OR ([name1] IS NULL AND @original_name1 IS NULL)) AND (([mail1] = @original_mail1) OR ([mail1] IS NULL AND @original_mail1 IS NULL)) AND (([word1] = @original_word1) OR ([word1] IS NULL AND @original_word1 IS NULL)) AND (([時間戳記] = @original_時間戳記) OR ([時間戳記] IS NULL AND @original_時間戳記 IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_識別碼" Type="Int32" />
                <asp:Parameter Name="original_name1" Type="String" />
                <asp:Parameter Name="original_mail1" Type="String" />
                <asp:Parameter Name="original_word1" Type="String" />
                <asp:Parameter Name="original_時間戳記" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="name1" Type="String" />
                <asp:Parameter Name="mail1" Type="String" />
                <asp:Parameter Name="word1" Type="String" />
                <asp:Parameter Name="時間戳記" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="name1" Type="String" />
                <asp:Parameter Name="mail1" Type="String" />
                <asp:Parameter Name="word1" Type="String" />
                <asp:Parameter Name="時間戳記" Type="String" />
                <asp:Parameter Name="original_識別碼" Type="Int32" />
                <asp:Parameter Name="original_name1" Type="String" />
                <asp:Parameter Name="original_mail1" Type="String" />
                <asp:Parameter Name="original_word1" Type="String" />
                <asp:Parameter Name="original_時間戳記" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <br />
        
        </span>
    
        <br />
       <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:pokomonConnectionString %>" SelectCommand="SELECT [識別碼], [name1], [mail1], [word1], [時間戳記] FROM [textmsg1] ORDER BY [識別碼]" ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM [textmsg1] WHERE [識別碼] = @original_識別碼 AND (([name1] = @original_name1) OR ([name1] IS NULL AND @original_name1 IS NULL)) AND (([mail1] = @original_mail1) OR ([mail1] IS NULL AND @original_mail1 IS NULL)) AND (([word1] = @original_word1) OR ([word1] IS NULL AND @original_word1 IS NULL)) AND (([時間戳記] = @original_時間戳記) OR ([時間戳記] IS NULL AND @original_時間戳記 IS NULL))" InsertCommand="INSERT INTO [textmsg1] ([name1], [mail1], [word1], [時間戳記]) VALUES (@name1, @mail1, @word1, @時間戳記)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [textmsg1] SET [name1] = @name1, [mail1] = @mail1, [word1] = @word1, [時間戳記] = @時間戳記 WHERE [識別碼] = @original_識別碼 AND (([name1] = @original_name1) OR ([name1] IS NULL AND @original_name1 IS NULL)) AND (([mail1] = @original_mail1) OR ([mail1] IS NULL AND @original_mail1 IS NULL)) AND (([word1] = @original_word1) OR ([word1] IS NULL AND @original_word1 IS NULL)) AND (([時間戳記] = @original_時間戳記) OR ([時間戳記] IS NULL AND @original_時間戳記 IS NULL))">
           <DeleteParameters>
               <asp:Parameter Name="original_識別碼" Type="Int32" />
               <asp:Parameter Name="original_name1" Type="String" />
               <asp:Parameter Name="original_mail1" Type="String" />
               <asp:Parameter Name="original_word1" Type="String" />
               <asp:Parameter Name="original_時間戳記" Type="String" />
           </DeleteParameters>
           <InsertParameters>
               <asp:Parameter Name="name1" Type="String" />
               <asp:Parameter Name="mail1" Type="String" />
               <asp:Parameter Name="word1" Type="String" />
               <asp:Parameter Name="時間戳記" Type="String" />
           </InsertParameters>
           <UpdateParameters>
               <asp:Parameter Name="name1" Type="String" />
               <asp:Parameter Name="mail1" Type="String" />
               <asp:Parameter Name="word1" Type="String" />
               <asp:Parameter Name="時間戳記" Type="String" />
               <asp:Parameter Name="original_識別碼" Type="Int32" />
               <asp:Parameter Name="original_name1" Type="String" />
               <asp:Parameter Name="original_mail1" Type="String" />
               <asp:Parameter Name="original_word1" Type="String" />
               <asp:Parameter Name="original_時間戳記" Type="String" />
           </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <br />
    
    </div>
    
    </form>
</body>
</html>
